-- minetest.register_alias("electrica:Quartz", "electrica:quartz") removed due to unnecessity
minetest.register_alias("electrica:QuartzBrick", "electrica:quartz_brick")
minetest.register_alias("electrica:QuartzPillar", "electrica:quartz_pillar")
minetest.register_alias("electrica:GravityQuartzBrick", "electrica:gravity_quartz_brick")
minetest.register_alias("electrica:QuartzChest", "electrica:quartz_ore")
minetest.register_alias("electrica:iron_gear", "electrica:steel_gear")
minetest.register_alias("electrica:quartz", "electrica:quartz_block")
minetest.register_alias("electrica_plastic:bucket_silicon", "electica:ep_bucket_silicon")
minetest.register_alias("electrica_plastic:silicon_ingot", "electrica:ep_silicon_ingot")
minetest.register_alias("electrica_plastic:bucket_plastidip", "electrica:ep_bucket_plastidip")
minetest.register_alias("electrica_plastic:nylon_ingot", "electrica:ep_nylon_ingot")
minetest.register_alias("electrica_plastic:silicon_node", "electrica:ep_silicon_node")
minetest.register_alias("electrica_plastic:plastic_source", "electrica:ep_silicon_source")
minetest.register_alias("electrica_plastic:plastic_flowing", "electrica:ep_silicon_flowing")
minetest.register_alias("electrica_plastic:bucket_plastic", "electrica:ep_bucket_silicon")
minetest.register_alias("electrica:ep_bucket_plastidip", "electrica:ep_bucket_silicon")
minetest.register_alias("electrica:ep_bucket_silicon1", "electrica:ep_bucket_silicon")
