dofile(minetest.get_modpath("electrica").."/nodes/quartzbase.lua")
dofile(minetest.get_modpath("electrica").."/nodes/quartz_block.lua")
dofile(minetest.get_modpath("electrica").."/nodes/quartz_brick.lua")
dofile(minetest.get_modpath("electrica").."/nodes/quartz_ore.lua")
dofile(minetest.get_modpath("electrica").."/nodes/quartz_pillar.lua")
dofile(minetest.get_modpath("electrica").."/nodes/gravity_quartz_brick.lua")
dofile(minetest.get_modpath("electrica").."/nodes/quartzbase.lua")