dofile(minetest.get_modpath("electrica").."/nodes/gearboxes.lua")
dofile(minetest.get_modpath("electrica").."/nodes/ores.lua")
dofile(minetest.get_modpath("electrica").."/nodes/quartznodes.lua")
dofile(minetest.get_modpath("electrica").."/nodes/ep_nodes.lua")
dofile(minetest.get_modpath("electrica").."/nodes/testnodes.lua")
